services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livego-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/livego.store-0001/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/livego.store-0001/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
