"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Battle = exports.UserActivity = exports.Withdrawal = exports.Like = exports.Follow = exports.BeautyEffect = exports.StreamKeyAssociation = exports.UserStatus = exports.ZoomSettings = exports.BannedEntity = exports.ManualTransmissao = exports.UserFrame = exports.Frame = exports.UserAvatar = exports.UserInventory = exports.ShopItem = exports.UserLevel = exports.MediaPermission = exports.AppVersion = exports.CoHostSession = exports.VideoQualitySettings = exports.BeautySettings = exports.GiftNotificationSettings = exports.UserIndex = exports.Visitor = exports.Invitation = exports.Conversation = exports.ChatMessage = exports.Chat = exports.ProfilePhoto = exports.Comment = exports.Birthday = exports.ProfileUpdate = exports.UserVideo = exports.UserPhoto = exports.Block = exports.Friendship = exports.Followers = exports.GiftTransaction = exports.StreamSession = exports.LiveNotification = exports.PurchaseRecord = exports.Photo = exports.Order = exports.Message = exports.Gift = exports.StreamLike = exports.StreamHistory = exports.Streamer = exports.User = void 0;
exports.ContentViolation = exports.StreamBan = exports.RouletteSpin = exports.RouletteItem = exports.StreamRoom = exports.PurchaseAuditTrail = exports.StreamParticipant = exports.EmptyApiLog = exports.PKInvite = exports.LiveCard = exports.LiveInvite = exports.LiveUser = exports.LiveMessage = exports.CallInvitation = exports.DeviceToken = void 0;
var User_1 = require("./User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_1.User; } });
var Streamer_1 = require("./Streamer");
Object.defineProperty(exports, "Streamer", { enumerable: true, get: function () { return Streamer_1.Streamer; } });
var StreamHistory_1 = require("./StreamHistory");
Object.defineProperty(exports, "StreamHistory", { enumerable: true, get: function () { return StreamHistory_1.StreamHistory; } });
var StreamLike_1 = require("./StreamLike");
Object.defineProperty(exports, "StreamLike", { enumerable: true, get: function () { return StreamLike_1.StreamLike; } });
var Gift_1 = require("./Gift");
Object.defineProperty(exports, "Gift", { enumerable: true, get: function () { return Gift_1.Gift; } });
var Message_1 = require("./Message");
Object.defineProperty(exports, "Message", { enumerable: true, get: function () { return Message_1.Message; } });
var Order_1 = require("./Order");
Object.defineProperty(exports, "Order", { enumerable: true, get: function () { return Order_1.Order; } });
var Photo_1 = require("./Photo");
Object.defineProperty(exports, "Photo", { enumerable: true, get: function () { return Photo_1.Photo; } });
var PurchaseRecord_1 = require("./PurchaseRecord");
Object.defineProperty(exports, "PurchaseRecord", { enumerable: true, get: function () { return PurchaseRecord_1.PurchaseRecord; } });
var LiveNotification_1 = require("./LiveNotification");
Object.defineProperty(exports, "LiveNotification", { enumerable: true, get: function () { return LiveNotification_1.LiveNotification; } });
var StreamSession_1 = require("./StreamSession");
Object.defineProperty(exports, "StreamSession", { enumerable: true, get: function () { return StreamSession_1.StreamSession; } });
var GiftTransaction_1 = require("./GiftTransaction");
Object.defineProperty(exports, "GiftTransaction", { enumerable: true, get: function () { return GiftTransaction_1.GiftTransaction; } });
var Followers_1 = require("./Followers");
Object.defineProperty(exports, "Followers", { enumerable: true, get: function () { return Followers_1.Followers; } });
var Friendship_1 = require("./Friendship");
Object.defineProperty(exports, "Friendship", { enumerable: true, get: function () { return Friendship_1.Friendship; } });
var Block_1 = require("./Block");
Object.defineProperty(exports, "Block", { enumerable: true, get: function () { return Block_1.Block; } });
var UserPhoto_1 = require("./UserPhoto");
Object.defineProperty(exports, "UserPhoto", { enumerable: true, get: function () { return UserPhoto_1.UserPhoto; } });
var UserVideo_1 = require("./UserVideo");
Object.defineProperty(exports, "UserVideo", { enumerable: true, get: function () { return UserVideo_1.UserVideo; } });
var ProfileUpdate_1 = require("./ProfileUpdate");
Object.defineProperty(exports, "ProfileUpdate", { enumerable: true, get: function () { return ProfileUpdate_1.ProfileUpdate; } });
var Birthday_1 = require("./Birthday");
Object.defineProperty(exports, "Birthday", { enumerable: true, get: function () { return Birthday_1.Birthday; } });
var Comment_1 = require("./Comment");
Object.defineProperty(exports, "Comment", { enumerable: true, get: function () { return Comment_1.Comment; } });
var ProfilePhoto_1 = require("./ProfilePhoto");
Object.defineProperty(exports, "ProfilePhoto", { enumerable: true, get: function () { return ProfilePhoto_1.ProfilePhoto; } });
var Chat_1 = require("./Chat");
Object.defineProperty(exports, "Chat", { enumerable: true, get: function () { return Chat_1.Chat; } });
var ChatMessage_1 = require("./ChatMessage");
Object.defineProperty(exports, "ChatMessage", { enumerable: true, get: function () { return ChatMessage_1.ChatMessage; } });
var Conversation_1 = require("./Conversation");
Object.defineProperty(exports, "Conversation", { enumerable: true, get: function () { return Conversation_1.Conversation; } });
var Invitation_1 = require("./Invitation");
Object.defineProperty(exports, "Invitation", { enumerable: true, get: function () { return Invitation_1.Invitation; } });
var Visitor_1 = require("./Visitor");
Object.defineProperty(exports, "Visitor", { enumerable: true, get: function () { return Visitor_1.Visitor; } });
var UserIndex_1 = require("./UserIndex");
Object.defineProperty(exports, "UserIndex", { enumerable: true, get: function () { return UserIndex_1.UserIndex; } });
var GiftNotificationSettings_1 = require("./GiftNotificationSettings");
Object.defineProperty(exports, "GiftNotificationSettings", { enumerable: true, get: function () { return GiftNotificationSettings_1.GiftNotificationSettings; } });
var BeautySettings_1 = require("./BeautySettings");
Object.defineProperty(exports, "BeautySettings", { enumerable: true, get: function () { return BeautySettings_1.BeautySettings; } });
var VideoQualitySettings_1 = require("./VideoQualitySettings");
Object.defineProperty(exports, "VideoQualitySettings", { enumerable: true, get: function () { return VideoQualitySettings_1.VideoQualitySettings; } });
var CoHostSession_1 = require("./CoHostSession");
Object.defineProperty(exports, "CoHostSession", { enumerable: true, get: function () { return CoHostSession_1.CoHostSession; } });
var AppVersion_1 = require("./AppVersion");
Object.defineProperty(exports, "AppVersion", { enumerable: true, get: function () { return AppVersion_1.AppVersion; } });
var UserPermissions_1 = require("./UserPermissions");
Object.defineProperty(exports, "MediaPermission", { enumerable: true, get: function () { return UserPermissions_1.MediaPermission; } });
var UserLevel_1 = require("./UserLevel"); // NOVO - Sistema de NÃ­vel
Object.defineProperty(exports, "UserLevel", { enumerable: true, get: function () { return UserLevel_1.UserLevel; } });
var ShopItem_1 = require("./ShopItem");
Object.defineProperty(exports, "ShopItem", { enumerable: true, get: function () { return ShopItem_1.ShopItem; } });
var UserInventory_1 = require("./UserInventory");
Object.defineProperty(exports, "UserInventory", { enumerable: true, get: function () { return UserInventory_1.UserInventory; } });
var UserAvatar_1 = require("./UserAvatar");
Object.defineProperty(exports, "UserAvatar", { enumerable: true, get: function () { return UserAvatar_1.UserAvatar; } });
var Frame_1 = require("./Frame");
Object.defineProperty(exports, "Frame", { enumerable: true, get: function () { return Frame_1.Frame; } });
var UserFrame_1 = require("./UserFrame");
Object.defineProperty(exports, "UserFrame", { enumerable: true, get: function () { return UserFrame_1.UserFrame; } });
var ManualTransmissao_1 = require("./ManualTransmissao");
Object.defineProperty(exports, "ManualTransmissao", { enumerable: true, get: function () { return ManualTransmissao_1.ManualTransmissao; } });
var BannedEntity_1 = require("./BannedEntity");
Object.defineProperty(exports, "BannedEntity", { enumerable: true, get: function () { return BannedEntity_1.BannedEntity; } });
var ZoomSettings_1 = require("./ZoomSettings");
Object.defineProperty(exports, "ZoomSettings", { enumerable: true, get: function () { return ZoomSettings_1.ZoomSettings; } });
var UserStatus_1 = require("./UserStatus");
Object.defineProperty(exports, "UserStatus", { enumerable: true, get: function () { return UserStatus_1.UserStatus; } });
var StreamKeyAssociation_1 = require("./StreamKeyAssociation");
Object.defineProperty(exports, "StreamKeyAssociation", { enumerable: true, get: function () { return StreamKeyAssociation_1.StreamKeyAssociation; } });
var BeautyEffect_1 = require("./BeautyEffect");
Object.defineProperty(exports, "BeautyEffect", { enumerable: true, get: function () { return BeautyEffect_1.BeautyEffect; } });
var Follow_1 = require("./Follow");
Object.defineProperty(exports, "Follow", { enumerable: true, get: function () { return Follow_1.Follow; } });
var Like_1 = require("./Like");
Object.defineProperty(exports, "Like", { enumerable: true, get: function () { return Like_1.Like; } });
var Withdrawal_1 = require("./Withdrawal");
Object.defineProperty(exports, "Withdrawal", { enumerable: true, get: function () { return Withdrawal_1.Withdrawal; } });
var UserActivity_1 = require("./UserActivity");
Object.defineProperty(exports, "UserActivity", { enumerable: true, get: function () { return UserActivity_1.UserActivity; } });
var Battle_1 = require("./Battle");
Object.defineProperty(exports, "Battle", { enumerable: true, get: function () { return Battle_1.Battle; } });
var DeviceToken_1 = require("./DeviceToken");
Object.defineProperty(exports, "DeviceToken", { enumerable: true, get: function () { return DeviceToken_1.DeviceToken; } });
var CallInvitation_1 = require("./CallInvitation");
Object.defineProperty(exports, "CallInvitation", { enumerable: true, get: function () { return CallInvitation_1.CallInvitation; } });
var LiveMessage_1 = require("./LiveMessage");
Object.defineProperty(exports, "LiveMessage", { enumerable: true, get: function () { return LiveMessage_1.LiveMessage; } });
var LiveInvite_1 = require("./LiveInvite");
Object.defineProperty(exports, "LiveUser", { enumerable: true, get: function () { return LiveInvite_1.LiveUser; } });
Object.defineProperty(exports, "LiveInvite", { enumerable: true, get: function () { return LiveInvite_1.LiveInvite; } });
var LiveCard_1 = require("./LiveCard");
Object.defineProperty(exports, "LiveCard", { enumerable: true, get: function () { return LiveCard_1.LiveCard; } });
var PKInvite_1 = require("./PKInvite");
Object.defineProperty(exports, "PKInvite", { enumerable: true, get: function () { return PKInvite_1.PKInvite; } });
var EmptyApiLog_1 = require("./EmptyApiLog");
Object.defineProperty(exports, "EmptyApiLog", { enumerable: true, get: function () { return EmptyApiLog_1.EmptyApiLog; } });
var StreamParticipant_1 = require("./StreamParticipant");
Object.defineProperty(exports, "StreamParticipant", { enumerable: true, get: function () { return StreamParticipant_1.StreamParticipant; } });
var PurchaseAuditTrail_1 = require("./PurchaseAuditTrail");
Object.defineProperty(exports, "PurchaseAuditTrail", { enumerable: true, get: function () { return PurchaseAuditTrail_1.PurchaseAuditTrail; } });
var StreamRoom_1 = require("./StreamRoom");
Object.defineProperty(exports, "StreamRoom", { enumerable: true, get: function () { return StreamRoom_1.StreamRoom; } });
var RouletteItem_1 = require("./RouletteItem");
Object.defineProperty(exports, "RouletteItem", { enumerable: true, get: function () { return RouletteItem_1.RouletteItem; } });
var RouletteSpin_1 = require("./RouletteSpin");
Object.defineProperty(exports, "RouletteSpin", { enumerable: true, get: function () { return RouletteSpin_1.RouletteSpin; } });
var StreamBan_1 = require("./StreamBan");
Object.defineProperty(exports, "StreamBan", { enumerable: true, get: function () { return StreamBan_1.StreamBan; } });
var ContentViolation_1 = require("./ContentViolation");
Object.defineProperty(exports, "ContentViolation", { enumerable: true, get: function () { return ContentViolation_1.ContentViolation; } });
